# Generated by Django 3.1.1 on 2020-10-13 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Компания')),
                ('location', models.CharField(blank=True, max_length=32, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, upload_to='logs/%Y/%m/%d/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Информация о компании')),
                ('employee_count', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=32, verbose_name='Специализация')),
                ('picture', models.ImageField(blank=True, upload_to='pics/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Профессия')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('level', models.CharField(max_length=16, verbose_name='Уровень')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='job.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='job.specialty')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('readiness', models.CharField(choices=[('consideration', 'Рассматриваю предложения'), ('not_in_search', 'Не ищу работу'), ('in_search', 'Ищу работу')], max_length=32, verbose_name='Готовность')),
                ('salary', models.PositiveIntegerField(verbose_name='Хочу')),
                ('level', models.CharField(choices=[('junior', 'junior'), ('lead', 'lead'), ('intern', 'intern'), ('middle', 'middle'), ('senior', 'senior')], max_length=32, verbose_name='Крутость')),
                ('education', models.CharField(choices=[('missing', 'Отсутствует'), ('vocational', 'Средне-специальное'), ('higher', 'Высшее'), ('incomplete_higher', 'Неполное высшее'), ('secondary', 'Среднее')], max_length=32, verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт')),
                ('portfolio', models.CharField(max_length=32)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.specialty', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=32, verbose_name='Вас зовут')),
                ('written_phone', models.CharField(max_length=32, verbose_name='Ваш телефон')),
                ('written_cover_letter', models.TextField(verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['written_username'],
            },
        ),
    ]
