# Generated by Django 3.1.1 on 2020-09-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Компания')),
                ('location', models.CharField(blank=True, max_length=32, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, upload_to='logs/%Y/%m/%d/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Информация о компании')),
                ('employee_count', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=32, verbose_name='Специализация')),
                ('picture', models.ImageField(blank=True, upload_to='pics/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Профессия')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('level', models.CharField(max_length=16, verbose_name='Уровень')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(verbose_name='Зарплата до')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='vacancies', to='job.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='vacancies', to='job.specialty')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
